# Generated by Django 2.2.6 on 2019-10-29 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('calificacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Flor',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('estado', models.TextField()),
                ('valor', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('stock', models.IntegerField()),
                ('fotografia', models.ImageField(null=True, upload_to='floor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floreria.Categoria')),
            ],
        ),
    ]
